services:
  node1:
    image: gossip-server
    build:
      dockerfile: Dockerfile
      context: .
    container_name: node1_container
    entrypoint: [ "java", "-jar", "-Dspring.profiles.active=first", "app.jar" ]
    networks:
      - boutade_network
    ports:
      - 1010:8080
  node2:
    image: gossip-server
    build:
      dockerfile: Dockerfile
      context: .
    container_name: node2_container
    entrypoint: [ "java", "-jar", "-Dspring.profiles.active=second", "app.jar" ]
    networks:
      - boutade_network
    ports:
      - 2020:8080
  node3:
    image: gossip-server
    build:
      dockerfile: Dockerfile
      context: .
    container_name: node3_container
    entrypoint: [ "java", "-jar", "-Dspring.profiles.active=third", "app.jar" ]
    networks:
      - boutade_network
    ports:
      - 3030:8080

networks:
  boutade_network:
    driver: bridge
    name: boutade_network