cluster:
  node-id: node-2
  failure-timeout: 30000
  address: localhost,9090
  members:
    - node-1,localhost,8080
spring:
  application:
    name: gossip
server:
  port: 9090
logging:
  level:
    root: INFO